// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core.Extensions;
using PetClient;

namespace Microsoft.Extensions.Azure
{
    /// <summary> Extension methods to add <see cref="PetClient.PetClient"/> to client builder. </summary>
    public static partial class PetClientBuilderExtensions
    {
        /// <summary> Registers a <see cref="PetClient"/> instance. </summary>
        /// <param name="builder"> The builder to register with. </param>
        /// <param name="endpoint"> server parameter. </param>
        public static IAzureClientBuilder<PetClient.PetClient, PetClientOptions> AddPetClient<TBuilder>(this TBuilder builder, Uri endpoint)
        where TBuilder : IAzureClientFactoryBuilder
        {
            return builder.RegisterClientFactory<PetClient.PetClient, PetClientOptions>((options) => new PetClient.PetClient(endpoint, options));
        }

        /// <summary> Registers a <see cref="PetClient"/> instance. </summary>
        /// <param name="builder"> The builder to register with. </param>
        /// <param name="configuration"> The configuration values. </param>
        public static IAzureClientBuilder<PetClient.PetClient, PetClientOptions> AddPetClient<TBuilder, TConfiguration>(this TBuilder builder, TConfiguration configuration)
        where TBuilder : IAzureClientFactoryBuilderWithConfiguration<TConfiguration>
        {
            return builder.RegisterClientFactory<PetClient.PetClient, PetClientOptions>(configuration);
        }
    }
}
