// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace PetClient
{
    /// <summary> Client options for PetClient. </summary>
    public partial class PetClientOptions : ClientOptions
    {
        private const ServiceVersion LatestVersion = ServiceVersion.V2_0;

        /// <summary> The version of the service to use. </summary>
        public enum ServiceVersion
        {
            /// <summary> Service version "2.0". </summary>
            V2_0 = 1,
        }

        internal string Version { get; }

        /// <summary> Initializes new instance of PetClientOptions. </summary>
        public PetClientOptions(ServiceVersion version = LatestVersion)
        {
            Version = version switch
            {
                ServiceVersion.V2_0 => "2.0",
                _ => throw new NotSupportedException()
            };
        }
    }
}
