# This is a basic workflow to help you get started with Actions

name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Delete existing client libraries
      run: |
        rm -rf client-libraries
        rm -rf client-libraries/csharp
        rm -rf client-libraries/typescript

    - name: Install AutoRest
      run: npm install autorest@latest -g

    - name: Generate C# client library
      run: autorest --input-file=api-spec.yaml --output-folder=client-libraries/csharp --csharp

    - name: Generate TypeScript client library
      run: autorest --input-file=api-spec.yaml --output-folder=client-libraries/typescript --typescript

    - name: Commit changes
      run: |
        git config --global user.email "test@example.com"
        git config --global user.name "test Name"
        git add .
        git commit -m "Update client libraries"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
