# This is a basic workflow to help you get started with Actions

name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: azsdkengsys.azurecr.io/azuresdk/autorest-all
    steps:
      - run: autorest --input-file=https://raw.githubusercontent.com/sauragrawa/Samplecodedownload/main/Pets.json?token=GHSAT0AAAAAABXBRFD4Y32ZHM3D2E4RUD2MYXKNOGA --csharp --output-folder=myFolder/
